// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OTL_API.Entities;
using System;

namespace OTL_API.Migrations
{
    [DbContext(typeof(TaskListContext))]
    [Migration("20180216092827_InitialTaskListDB")]
    partial class InitialTaskListDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OTL_API.Entities.TaskList", b =>
                {
                    b.Property<Guid>("TaskListID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDone");

                    b.Property<string>("Title");

                    b.Property<int>("UserID");

                    b.HasKey("TaskListID");

                    b.ToTable("TaskLists");
                });
#pragma warning restore 612, 618
        }
    }
}
